server:
  port: 8081

logging:
  level:
    org:
      springframework:
        data: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false

spring:
  data:
    mongodb:
      uri: mongodb://city:123@localhost:27017/city