server:
  port: 8082

logging:
  level:
    org:
      springframework:
        data: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false