version: '3'

services:
  route:
    image: route:master
    ports:
    - 8081:8081
    links:
    - route-mongodb
    environment:
      PROFILE: "dev"
  route-mongodb:
    image: mongo:3.4.2
    ports:
    - 27017:27017
    command: mongod --smallfiles
