server:
  port: 8088

logging:
  level:
    org:
      springframework:
        data: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    itinerary:
      path: /itinerary/**
      serviceId: itinerary
    route:
      path: /route/**
      serviceId: route
