server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/